apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment-episode-04
  namespace: development
spec:
  replicas: 3
  selector:
    matchLabels:
      app: backend-episode-04
  template:
    metadata:
      labels:
        app: backend-episode-04
    spec:
      containers:
      - name: backend
        image: murtazahasan/backend-episode-04:latest
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service-episode-04
  namespace: development
spec:
  selector:
    app: backend-episode-04
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
