apiVersion: v1
kind: PersistentVolume
metadata:
  name: database-pv-episode-02
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data/episode-02"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: database-pvc-episode-02
  namespace: development
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
